### ISSUE TITLE
TrieDedup collapsing?

### ISSUE THREAD

**Issue by BiotechPedro** [lolrenceH/TrieDedup#1]
Hi! :D 

I have come across you cool algorithm and I was wondering if there is a way for using it in barcode sequence collapsing (no Ns in the sequences and length of ~35 nucleotides) or by the contrary I am wrong an your algorithm cannot work as [UMIClusterer from UMItools](https://umi-tools.readthedocs.io/en/latest/API.html) or [UMICollapse](https://github.com/Daniel-Liu-c0deb0t/UMICollapse).

Thank you a lot!!

Pedro

**Comment by Yyx2626** [comment]
Hi Pedro,

Thank you for your interests in our tool.  The algorithm can be potentially extended to apply to UMIs, which has not been implemented in current version yet.  In my opinion, sequences without ambiguous Ns can be simply and efficiently deduplicated by hash, so our tool focuses on the harder problem with ambiguous Ns.  We may extend it for UMIs and include another branch of hash deduplication for not allowing Ns in the future version, but current version may be slower due to careful checking possible Ns.

Best regards,
Adam Yongxin Ye

**Comment by BiotechPedro** [comment]
Thank you for the clear respose! 

Best :D

Pedro
